INSERT INTO appearances (entity_id, app_name)
VALUES	('Favorites'),
		('Main Characters'),
		('Side Characters'),
		('Fixer'),
		('Ripperdoc'),
		('Arasaka'),
		('Nomad'),
		('Valentinos'),
		('Voodoo Boys'),
		('Tyger Claws'),
		('Animals'),
		('6th Street'),
		('Maelstrom'),
		('Mox'),
		('Samurai'),
		('NCPD'),
		('Netwatch'),
		('Trauma Team'),
		('Militech'),
		('Kang Tao'),
		('Cyberpsycho'),
		('Cameos'),
		('Misc. NPCs'),
		('Vehicles')
		('At Your Own Risk');